version: '3.8'

services:
  # --- DATABASE SERVICE ---
  mysql:
    image: mysql:8
    container_name: food-app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Prudhviraj@310
      MYSQL_DATABASE: fooddb
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # --- BACKEND SERVICE ---
  backend:
    build: ./backend
    container_name: food-app-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Prudhviraj@310
      DB_NAME: fooddb

  # --- FRONTEND SERVICE ---
  frontend:
    build: ./frontend
    container_name: food-app-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # --- JENKINS (CI/CD) SERVICE ---
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root  # FIX: Runs as root so it always has permission to use docker.sock
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock      # Mounts Host Docker into Jenkins
      - /home/ubuntu/.kube/config:/var/jenkins_home/.kube/config  # Mounts K8s Config into Jenkins
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Optional: skips initial setup if already done

volumes:
  jenkins_home: