apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: prudhviraj310/food-app-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "food-app-db"
---
apiVersion: v1
kind: Service
metadata:
  name: food-app-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080