apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: prudhviraj310/food-app-backend:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "food-app-db"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: food-app-backend
spec:
  type: NodePort  # Added this to make it accessible from Chrome
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008 # Use this port in Chrome